churn_analytics_platform:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: /workspaces/churn-analytics-platform/duckdb/churn_warehouse.duckdb
      schema: staging
      threads: 1

    prod:
      type: duckdb
      path: /workspaces/churn-analytics-platform/duckdb/churn_warehouse.duckdb
      schema: production
      threads: 4
