name: 'churn_analytics'
version: '1.0.0'
config-version: 2

profile: 'churn_analytics'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  churn_analytics:
    staging:
      +materialized: view
      +tags: ['staging']
      +schema: staging
    
    intermediate:
      +materialized: view
      +tags: ['intermediate']
      +schema: intermediate
    
    marts:
      +materialized: table
      +tags: ['marts']
      +schema: marts
